### ISSUE TITLE
Difficulties in the Beginning / Schwierigkeiten am Anfang

### ISSUE THREAD

**Issue by TaddLab** [StefanSchmelz/AnfaenngerFragen#1]
Important are EXAMPELS and/or slow step by step coding (without jumping over too many steps), especially if you are a Beginner or currently try to learn a difficult new topic like  : 

-> Generic-Programming and Polymorphism (JAVA) 
-> Graphs in (Python)
-> Pointers in ( in C )

Besonders wichtig finde ich BEISPIELE und/oder step by step coding (ohne viele Schritte zu überspringen), besonders wenn du ein Anfänger bist oder gerade versuchst ein schwieriges neues Thema lernst wie: (siehe MITTE)

**Comment by NeoCortex97** [comment]
fixed by adding your suggestions to the general category
